# Datasource Configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/gestor_mei?createDatabaseIfNotExist=true
quarkus.datasource.db-version=5.5.5

# Hibernate Configuration
quarkus.hibernate-orm.database.version-check.enabled=false
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.database.generation=create
quarkus.hibernate-orm.database.generation.create-schemas=true

# CORS Configuration
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

## JWT Configuration
mp.jwt.verify.issuer=gestor-mei
mp.jwt.verify.audiences=gestor-mei-app
smallrye.jwt.sign.key.location=/privateKey.pem
mp.jwt.verify.publickey.location=/publicKey.pem

# OpenAPI / Swagger
quarkus.swagger-ui.always-include=true

# Logging
quarkus.log.level=INFO
